# Site settings
title: Microwavegan Time
email: admin@microwavegan.com
author: ""
description: Easy vegan. Duh.
baseurl: ""
url: "http://microwavegan.com"

image: apple-touch-icon-180x180.png
# Build settings
markdown: kramdown

permalink: pretty
sass:
    sass_dir: bower_components/foundation/scss
    style: compressed

exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
    - bower.json
    - node_modules/*

